In [4]:
import torch

x = torch.randn(2, 3)
mask = torch.tensor([True, False, True])  # shape (3,)
x.masked_fill(mask, 0)  # ❌ 错，因为 (3,) 无法广播到 (2, 3)

a = torch.rand((3, 5))
print(a)
print(a.unsqueeze(1))
print(a.unsqueeze(1).unsqueeze(-1))

tensor([[0.3969, 0.2800, 0.8349, 0.2901, 0.6935],
        [0.8142, 0.6477, 0.4673, 0.2253, 0.5960],
        [0.6400, 0.8461, 0.3737, 0.8131, 0.2501]])
tensor([[[0.3969, 0.2800, 0.8349, 0.2901, 0.6935]],

        [[0.8142, 0.6477, 0.4673, 0.2253, 0.5960]],

        [[0.6400, 0.8461, 0.3737, 0.8131, 0.2501]]])
tensor([[[[0.3969],
          [0.2800],
          [0.8349],
          [0.2901],
          [0.6935]]],


        [[[0.8142],
          [0.6477],
          [0.4673],
          [0.2253],
          [0.5960]]],


        [[[0.6400],
          [0.8461],
          [0.3737],
          [0.8131],
          [0.2501]]]])


In [9]:
import torch

attn_output_weights = torch.tensor([
    [1.2, 0.3, 0.4, 0.2, 0.1],  # token 0
    [0.3, 1.0, 0.6, 0.5, 0.1],  # token 1
    [0.4, 0.6, 1.3, 0.7, 0.2],  # token 2
    [0.2, 0.5, 0.7, 1.1, 0.4],  # token 3
    [0.1, 0.1, 0.2, 0.4, 1.5]   # token 4 (padding)
])
key_padding_mask = torch.tensor([[False, False, False, False, True]])  # 只有最后一个 token 是 padding
# print(key_padding_mask)
attn_output_weights = attn_output_weights.masked_fill(key_padding_mask.unsqueeze(1).unsqueeze(2) == 1, float('-inf'))
print(attn_output_weights)

tensor([[[[1.2000, 0.3000, 0.4000, 0.2000,   -inf],
          [0.3000, 1.0000, 0.6000, 0.5000,   -inf],
          [0.4000, 0.6000, 1.3000, 0.7000,   -inf],
          [0.2000, 0.5000, 0.7000, 1.1000,   -inf],
          [0.1000, 0.1000, 0.2000, 0.4000,   -inf]]]])
